aws:
  access_key_id: <%= ENV['S3_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>
  region: <%= ENV['S3_AWS_REGION'] %>
  receive_message:              # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Queue.html#receive_messages-instance_method
    wait_time_seconds: 1        # The number of seconds to wait for new messages when polling. Defaults to the #wait_time_seconds defined on the queue
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
concurrency: 25  # The number of allocated threads to process messages. Default 25
delay: 10        # The delay in seconds to pause a queue when it's empty. Default 0
timeout: 8
queues:
  - [START_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 1]
  - [HARVEST_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 3]
  - [TRANSCODE_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 3]
  - [SPLIT_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 3]
  - [CROWDOUT_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 3]
  - [ARCHIVE_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 3]
  - [FINISH_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 1]
  - [STOP_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 1]
  - [RESET_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 1]
  - [REMOVE_<%= ENV.fetch('CPW_ENV', 'development').upcase %>_QUEUE, 1]
