aws:
  access_key_id: <%= ENV['S3_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>
  #region: abcd #<%= ENV['AWS_REGION'] %>
  receive_message:              # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Queue.html#receive_messages-instance_method
    wait_time_seconds: 10       # The number of seconds to wait for new messages when polling. Defaults to the #wait_time_seconds defined on the queue
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
concurrency: 25  # The number of allocated threads to process messages. Default 25
delay: 25        # The delay in seconds to pause a queue when it's empty. Default 0
queues:
  - [HARVEST_DEVELOPMENT_QUEUE, 4]
  - [TRANSCODE_DEVELOPMENT_QUEUE, 10]
  - [TRANSCRIBE_DEVELOPMENT_QUEUE, 10]
  - [ARCHIVE_DEVELOPMENT_QUEUE, 1]
